import { supabase } from '@/integrations/supabase/client'
import type { AlertActionTaken, AlertInaccuracyReason, AlertWithFeedback } from '@/types/database'

// Autogenerated Supabase types can lag partner QA views/tables; keep the same
// pragmatic cast pattern used by the rest of this app's query layer.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const sb = supabase as any
export const ACHIEVE_MODULE_NAME = 'achieve_welcome_call_qa'
const showDemoData = import.meta.env.VITE_ACHIEVE_DEMO_DATA === 'true'

type AchieveModuleResultRow = {
  id: number
  created_at: string | null
  call_id: string
  module_name: string
  violation_type: string | null
  has_violation: boolean | null
  alert_sent: boolean | null
  alert_sent_at: string | null
  agent_email: string | null
  contact_name: string | null
  contact_phone: string | null
  recording_link: string | null
  transcript_url: string | null
  call_summary: string | null
  sfdc_lead_id: string | null
  processing_time_ms: number | null
  result_json: any
}

type AchieveTranscriptRow = {
  call_id: string | null
  original_transcript: string | null
  transcription_link: string | null
  recording_link: string | null
}

type AchieveFeedbackRow = {
  id: number
  call_id: string
  module_name: string
  manager_email: string | null
  accurate: boolean | null
  action_taken: AlertActionTaken | null
  inaccuracy_reason: AlertInaccuracyReason | null
  comment: string | null
  reviewed_at: string | null
}

export type AchieveReviewFeedbackInput = {
  call_id: string
  module_name: string
  reviewer_email: string
  accurate: boolean
  action_taken?: AlertActionTaken | null
  inaccuracy_reason?: AlertInaccuracyReason | null
  comment?: string | null
}

export async function fetchAchieveAlerts(limit = 100): Promise<AlertWithFeedback[]> {
  const { data, error } = await sb
    .from('eavesly_alerts_with_feedback')
    .select('*')
    .eq('module_name', ACHIEVE_MODULE_NAME)
    .order('alert_created_at', { ascending: false })
    .limit(limit)

  if (error) {
    console.error('Error fetching Achieve QA alerts:', error)
    if (showDemoData) return [achieveDemoAlert]
    throw error
  }

  const alerts = (data ?? []) as AlertWithFeedback[]
  if (alerts.length === 0 && showDemoData) return [achieveDemoAlert]
  return enrichAchieveRows(alerts)
}

export async function fetchAchieveAllCalls(limit = 100): Promise<AlertWithFeedback[]> {
  const { data, error } = await sb
    .from('eavesly_module_results')
    .select('*')
    .eq('module_name', ACHIEVE_MODULE_NAME)
    .order('created_at', { ascending: false })
    .limit(limit)

  if (error) {
    console.error('Error fetching Achieve QA calls:', error)
    if (showDemoData) return [achieveDemoAlert]
    throw error
  }

  const rows = ((data ?? []) as AchieveModuleResultRow[]).map(moduleResultToAlertRow)
  if (rows.length === 0 && showDemoData) return [achieveDemoAlert]
  return enrichAchieveRows(rows)
}

export async function submitAchieveReviewFeedback(
  input: AchieveReviewFeedbackInput,
): Promise<{ ok: boolean; error?: string }> {
  const payload = {
    call_id: input.call_id,
    module_name: input.module_name,
    manager_email: input.reviewer_email.trim(),
    accurate: input.accurate,
    action_taken: input.accurate ? input.action_taken ?? null : null,
    inaccuracy_reason: !input.accurate ? input.inaccuracy_reason ?? null : null,
    comment: input.comment?.trim() || null,
    reviewed_at: new Date().toISOString(),
  }

  const { error } = await sb
    .from('eavesly_alert_feedback')
    .upsert(payload, { onConflict: 'call_id,module_name' })

  if (error) {
    console.error('Error submitting Achieve QA feedback:', error)
    if (error.code === '42501') {
      return {
        ok: false,
        error: 'Feedback needs an authenticated server/API endpoint before this password-gated scaffold can save reviewer notes.',
      }
    }
    return { ok: false, error: error.message }
  }
  return { ok: true }
}

async function enrichAchieveRows(rows: AlertWithFeedback[]): Promise<AlertWithFeedback[]> {
  const callIds = Array.from(new Set(rows.map(row => row.call_id).filter(Boolean)))
  if (callIds.length === 0) return rows

  const [transcriptsRes, feedbackRes] = await Promise.all([
    sb
      .from('eavesly_transcription_qa')
      .select('call_id,original_transcript,transcription_link,recording_link')
      .in('call_id', callIds),
    sb
      .from('eavesly_alert_feedback')
      .select('id,call_id,module_name,manager_email,accurate,action_taken,inaccuracy_reason,comment,reviewed_at')
      .eq('module_name', ACHIEVE_MODULE_NAME)
      .in('call_id', callIds),
  ])

  if (transcriptsRes.error) {
    console.error('Error fetching Achieve transcripts:', transcriptsRes.error)
  }
  if (feedbackRes.error) {
    console.error('Error fetching Achieve feedback:', feedbackRes.error)
  }

  const transcriptByCall = new Map(
    ((transcriptsRes.data ?? []) as AchieveTranscriptRow[])
      .filter(row => row.call_id)
      .map(row => [row.call_id as string, row]),
  )
  const feedbackByCall = new Map(
    ((feedbackRes.data ?? []) as AchieveFeedbackRow[])
      .filter(row => row.call_id)
      .map(row => [row.call_id, row]),
  )

  return rows.map(row => {
    const transcript = transcriptByCall.get(row.call_id)
    const feedback = feedbackByCall.get(row.call_id)
    return {
      ...row,
      recording_link: row.recording_link ?? transcript?.recording_link ?? null,
      transcript_url: row.transcript_url ?? transcript?.transcription_link ?? null,
      original_transcript: transcript?.original_transcript ?? null,
      feedback_id: feedback?.id ?? row.feedback_id,
      feedback_by: feedback?.manager_email ?? row.feedback_by,
      accurate: feedback?.accurate ?? row.accurate,
      action_taken: feedback?.action_taken ?? row.action_taken,
      inaccuracy_reason: feedback?.inaccuracy_reason ?? row.inaccuracy_reason,
      feedback_comment: feedback?.comment ?? row.feedback_comment,
      reviewed_at: feedback?.reviewed_at ?? row.reviewed_at,
      is_reviewed: !!(feedback?.reviewed_at ?? row.reviewed_at),
    }
  })
}

function moduleResultToAlertRow(row: AchieveModuleResultRow): AlertWithFeedback {
  return {
    module_result_id: row.id,
    alert_created_at: row.created_at ?? new Date(0).toISOString(),
    alert_sent_at: row.alert_sent_at,
    call_id: row.call_id,
    module_name: row.module_name,
    violation_type: row.violation_type ?? 'achieve_welcome_call',
    has_violation: row.has_violation ?? false,
    alert_sent: row.alert_sent ?? false,
    agent_email: row.agent_email,
    contact_name: row.contact_name,
    contact_phone: row.contact_phone,
    recording_link: row.recording_link,
    transcript_url: row.transcript_url,
    call_summary: row.call_summary,
    sfdc_lead_id: row.sfdc_lead_id,
    processing_time_ms: row.processing_time_ms,
    result_json: row.result_json,
    assigned_manager_email: null,
    feedback_id: null,
    feedback_by: null,
    accurate: null,
    action_taken: null,
    inaccuracy_reason: null,
    feedback_comment: null,
    reviewed_at: null,
    is_reviewed: false,
    message_count: 0,
    last_message_at: null,
    acker_emails: [],
  }
}

const achieveDemoAlert: AlertWithFeedback = {
  module_result_id: -1,
  alert_created_at: '2026-06-29T18:00:00.000Z',
  alert_sent_at: null,
  call_id: 'WT8ace5e457629417521644859dcb187ca',
  module_name: ACHIEVE_MODULE_NAME,
  violation_type: 'script_adherence',
  has_violation: false,
  alert_sent: false,
  agent_email: 'demo-achieve@example.invalid',
  contact_name: 'Demo client',
  contact_phone: null,
  recording_link: null,
  transcript_url: null,
  call_summary: 'DEMO DATA: Client completed FDR enrollment handoff and welcome call; app/dashboard setup was completed, program basics were reviewed, and customer service contact information was provided.',
  sfdc_lead_id: null,
  processing_time_ms: null,
  result_json: {
    demo_data: true,
    script_version: 'fdr_wholesale_db_pilot_v0',
    script_adherence: {
      welcome_greeting_completed: true,
      program_overview_covered: true,
      timeline_expectations_covered: true,
      payment_process_explained: true,
      client_communication_process_covered: true,
      next_steps_provided: true,
      overall_script_adherence: 'full',
      missing_elements: [],
      key_evidence_quotes: [
        'My name again is Max. I am a client success advocate, and I\'m excited to get to help you get started with your program today.',
        'Starting today, instead of making monthly payments to your enrolled creditors, you\'ll be making automatic deposits into your dedicated account.',
        'Before I let you go, I do have the Freedom Debt Relief customer service number in case you\'d like to write that down. Call at any time you have questions in the future.',
      ],
      violation: false,
      violation_reason: 'Demo output for UI validation. No violation: the welcome-call coordinator covered welcome, dashboard setup, payment process, program overview, client communication guidance, and next steps.',
    },
    assessment_confidence: {
      score: 0.86,
      level: 'high',
      rationale: 'DEMO DATA: Transcript clearly captured all required welcome-call elements with verbatim agent quotes; audio quality and segmentation were clean.',
      limitations: [
        'DEMO DATA: Client side of the call was partially inaudible during the payment-process explanation.',
      ],
    },
    transcript_segment: {
      segment_type: 'fdr_disclosure_and_welcome_call',
      start_line: 42,
      marker: 'My name again is Max. I am a client success advocate',
      segmentation_confidence: 'high',
      segmentation_score: 0.91,
      used_full_transcript_fallback: false,
    },
  },
  assigned_manager_email: null,
  feedback_id: null,
  feedback_by: null,
  accurate: null,
  action_taken: null,
  inaccuracy_reason: null,
  feedback_comment: null,
  reviewed_at: null,
  is_reviewed: false,
  message_count: 0,
  last_message_at: null,
  acker_emails: [],
}
