import { supabase } from '@/integrations/supabase/client'
import type { AlertWithFeedback } from '@/types/database'

// Autogenerated Supabase types can lag partner QA views/tables; keep the same
// pragmatic cast pattern used by the rest of this app's query layer.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const sb = supabase as any
export const ACHIEVE_MODULE_NAME = 'achieve_welcome_call_qa'

export async function fetchAchieveAlerts(limit = 100): Promise<AlertWithFeedback[]> {
  const { data, error } = await sb
    .from('eavesly_alerts_with_feedback')
    .select('*')
    .eq('module_name', ACHIEVE_MODULE_NAME)
    .order('alert_created_at', { ascending: false })
    .limit(limit)

  if (error) {
    console.error('Error fetching Achieve QA alerts:', error)
    throw error
  }
  return (data ?? []) as AlertWithFeedback[]
}
