import { supabase } from '@/integrations/supabase/client'
import type {
  AlertAck,
  AlertMessage,
  AlertWithFeedback,
  AlertFeedbackInput,
} from '@/types/database'
import { fetchAllPaginated } from './supabase-helpers'
import { startOfBusinessDay, endOfBusinessDay } from './time-zone'
import {
  ALWAYS_SUPPRESSED_ALERT_MODULES,
  SUPER_ADMIN_ONLY_ALERT_MODULES,
  filterSuppressedAlertRows,
  isSuppressedAlertModule,
} from './suppressed-alerts'

// The Database<> type is autogenerated and may not yet include the new view +
// table created in 20260427120000_eavesly_alert_feedback.sql. Until types are
// regenerated, we cast at call sites — same pragmatic approach the rest of
// this codebase uses.
const sb = supabase as any

export type UserScope = {
  email: string
  isGodMode: boolean
  managedAgents: string[]
}

export async function fetchUserScope(email: string): Promise<UserScope> {
  const [agentsRes, promptRes] = await Promise.all([
    sb
      .from('agent_manager_mapping')
      .select('agent_email')
      .eq('manager_email', email),
    sb
      .from('manager_coaching_prompts')
      .select('is_god_mode')
      .eq('manager_email', email)
      .maybeSingle(),
  ])

  if (agentsRes.error) {
    console.error('Error fetching agent_manager_mapping for scope:', agentsRes.error)
    throw agentsRes.error
  }
  if (promptRes.error) {
    console.error('Error fetching manager_coaching_prompts for scope:', promptRes.error)
    throw promptRes.error
  }

  return {
    email,
    isGodMode: !!promptRes?.data?.is_god_mode,
    managedAgents: (agentsRes?.data ?? []).map((a: any) => a.agent_email),
  }
}

export type AlertFilters = {
  startDate: Date
  endDate: Date
  modules?: string[]
  status?: 'all' | 'new' | 'reviewed'
  accuracy?: 'all' | 'accurate' | 'inaccurate'
  search?: string
}

// Columns rendered in the alerts table. Crucially excludes result_json,
// recording_link, transcript_url — those are only needed when the drawer
// opens and are fetched on demand via fetchAlertOne.
const ALERT_LIST_COLUMNS = [
  'call_id',
  'module_name',
  'violation_type',
  'alert_created_at',
  'has_violation',
  'alert_sent',
  'agent_email',
  'contact_name',
  'contact_phone',
  'call_summary',
  'sfdc_lead_id',
  'is_reviewed',
  'accurate',
  'action_taken',
  'inaccuracy_reason',
  'feedback_id',
  'feedback_by',
  'feedback_comment',
  'reviewed_at',
  'message_count',
  'last_message_at',
  'acker_emails',
].join(',')

export async function fetchAlerts(
  filters: AlertFilters,
  scope: UserScope,
): Promise<AlertWithFeedback[]> {
  // Manager with no mapped agents (and not god-mode) sees nothing.
  if (!scope.isGodMode && scope.managedAgents.length === 0) return []

  let q = sb
    .from('eavesly_alerts_with_feedback')
    .select(ALERT_LIST_COLUMNS)
    .gte('alert_created_at', startOfBusinessDay(filters.startDate).toISOString())
    .lte('alert_created_at', endOfBusinessDay(filters.endDate).toISOString())
    .order('alert_created_at', { ascending: false })
    .limit(500)

  // Disposition review is being tested in production. Keep its rows out of the
  // manager-facing alert queue until ops is ready to expose them.
  for (const moduleName of ALWAYS_SUPPRESSED_ALERT_MODULES) {
    q = q.neq('module_name', moduleName)
  }
  if (!scope.isGodMode) {
    for (const moduleName of SUPER_ADMIN_ONLY_ALERT_MODULES) {
      q = q.neq('module_name', moduleName)
    }
  }

  if (!scope.isGodMode) {
    q = q.in('agent_email', scope.managedAgents)
  }

  if (filters.modules?.length) q = q.in('module_name', filters.modules)
  if (filters.status === 'new') q = q.eq('is_reviewed', false)
  if (filters.status === 'reviewed') q = q.eq('is_reviewed', true)
  if (filters.accuracy === 'accurate') q = q.eq('accurate', true)
  if (filters.accuracy === 'inaccurate') q = q.eq('accurate', false)

  // Search is applied client-side now (small result set, removes per-keystroke
  // round-trip). The `search` field is ignored here intentionally.

  const { data, error } = await q
  if (error) {
    console.error('Error fetching alerts:', error)
    throw error
  }
  return filterSuppressedAlertRows(data as AlertWithFeedback[], scope)
}

// All alerts (any status, includes false-positives + non-violations) for a
// single call. Used on the call detail page so users can see whether Eavesly
// fired anything for this call.
export async function fetchAlertsForCall(
  callId: string,
  scope?: UserScope | null,
): Promise<AlertWithFeedback[]> {
  let q = sb
    .from('eavesly_alerts_with_feedback')
    .select('*')
    .eq('call_id', callId)
    .order('alert_created_at', { ascending: true })

  for (const moduleName of ALWAYS_SUPPRESSED_ALERT_MODULES) {
    q = q.neq('module_name', moduleName)
  }
  if (!scope?.isGodMode) {
    for (const moduleName of SUPER_ADMIN_ONLY_ALERT_MODULES) {
      q = q.neq('module_name', moduleName)
    }
  }

  const { data, error } = await q
  if (error) {
    console.error('Error fetching alerts for call:', error)
    throw error
  }
  return filterSuppressedAlertRows(data as AlertWithFeedback[], scope)
}

export async function fetchAlertOne(
  callId: string,
  moduleName: string,
  scope?: UserScope | null,
): Promise<AlertWithFeedback | null> {
  if (isSuppressedAlertModule(moduleName, scope)) return null

  const { data, error } = await sb
    .from('eavesly_alerts_with_feedback')
    .select('*')
    .eq('call_id', callId)
    .eq('module_name', moduleName)
    .maybeSingle()
  if (error) {
    console.error('Error fetching alert:', error)
    throw error
  }
  return (data as AlertWithFeedback) ?? null
}

export async function submitAlertFeedback(
  input: AlertFeedbackInput,
  scope?: UserScope | null,
): Promise<{ ok: boolean; error?: string }> {
  if (isSuppressedAlertModule(input.module_name, scope)) {
    return { ok: false, error: 'This alert type is hidden while it is in testing.' }
  }

  const payload = {
    call_id: input.call_id,
    module_name: input.module_name,
    manager_email: input.manager_email,
    accurate: input.accurate,
    action_taken: input.accurate ? input.action_taken ?? null : null,
    inaccuracy_reason: !input.accurate ? input.inaccuracy_reason ?? null : null,
    comment: input.comment?.trim() || null,
    reviewed_at: new Date().toISOString(),
  }
  const { error } = await sb
    .from('eavesly_alert_feedback')
    .upsert(payload, { onConflict: 'call_id,module_name' })
  if (error) {
    console.error('Error submitting feedback:', error)
    return { ok: false, error: error.message }
  }
  return { ok: true }
}

// ---- thread + acks ----

export type AlertThread = {
  messages: AlertMessage[]
  acks: AlertAck[]
}

export async function fetchAlertThread(
  callId: string,
  moduleName: string,
  scope?: UserScope | null,
): Promise<AlertThread> {
  if (isSuppressedAlertModule(moduleName, scope)) return { messages: [], acks: [] }

  const [messagesRes, acksRes] = await Promise.all([
    sb
      .from('eavesly_alert_messages')
      .select('*')
      .eq('call_id', callId)
      .eq('module_name', moduleName)
      .order('posted_at', { ascending: true }),
    sb
      .from('eavesly_alert_acks')
      .select('*')
      .eq('call_id', callId)
      .eq('module_name', moduleName)
      .order('acknowledged_at', { ascending: true }),
  ])
  if (messagesRes.error) {
    console.error('Error fetching alert messages:', messagesRes.error)
    throw messagesRes.error
  }
  if (acksRes.error) {
    console.error('Error fetching alert acks:', acksRes.error)
    throw acksRes.error
  }
  return {
    messages: (messagesRes.data || []) as AlertMessage[],
    acks: (acksRes.data || []) as AlertAck[],
  }
}

export async function postAlertMessage(input: {
  call_id: string
  module_name: string
  author_email: string
  body: string
  parent_message_id?: number | null
  requires_acknowledgment?: boolean
}): Promise<{ ok: boolean; message?: AlertMessage; error?: string }> {
  if (isSuppressedAlertModule(input.module_name)) {
    return { ok: false, error: 'This alert type is hidden while it is in testing.' }
  }

  const { data, error } = await sb
    .from('eavesly_alert_messages')
    .insert({
      call_id: input.call_id,
      module_name: input.module_name,
      author_email: input.author_email,
      body: input.body.trim(),
      parent_message_id: input.parent_message_id ?? null,
      requires_acknowledgment: input.requires_acknowledgment ?? false,
    })
    .select()
    .single()
  if (error) {
    console.error('Error posting alert message:', error)
    return { ok: false, error: error.message }
  }
  return { ok: true, message: data as AlertMessage }
}

export async function editAlertMessage(
  messageId: number,
  body: string,
): Promise<{ ok: boolean; error?: string }> {
  const { error } = await sb
    .from('eavesly_alert_messages')
    .update({ body: body.trim(), edited_at: new Date().toISOString() })
    .eq('id', messageId)
  if (error) {
    console.error('Error editing alert message:', error)
    return { ok: false, error: error.message }
  }
  return { ok: true }
}

export async function softDeleteAlertMessage(
  messageId: number,
): Promise<{ ok: boolean; error?: string }> {
  const { error } = await sb
    .from('eavesly_alert_messages')
    .update({ deleted_at: new Date().toISOString() })
    .eq('id', messageId)
  if (error) {
    console.error('Error deleting alert message:', error)
    return { ok: false, error: error.message }
  }
  return { ok: true }
}

export async function setAlertAck(input: {
  call_id: string
  module_name: string
  acker_email: string
  acked: boolean
}): Promise<{ ok: boolean; error?: string }> {
  if (isSuppressedAlertModule(input.module_name)) {
    return { ok: false, error: 'This alert type is hidden while it is in testing.' }
  }

  if (input.acked) {
    const { error } = await sb.from('eavesly_alert_acks').insert({
      call_id: input.call_id,
      module_name: input.module_name,
      acker_email: input.acker_email,
    })
    // 23505 = unique violation; idempotent ack toggle, treat as success.
    if (error && (error as any).code !== '23505') {
      console.error('Error setting alert ack:', error)
      return { ok: false, error: error.message }
    }
    return { ok: true }
  }
  const { error } = await sb
    .from('eavesly_alert_acks')
    .delete()
    .eq('call_id', input.call_id)
    .eq('module_name', input.module_name)
    .eq('acker_email', input.acker_email)
  if (error) {
    console.error('Error clearing alert ack:', error)
    return { ok: false, error: error.message }
  }
  return { ok: true }
}

// ---- team breakdown (heatmap) ----

export type AlertBreakdownCell = {
  module: string
  agent_email: string
  agent_full_name: string | null
  total: number // total violations in window
  unreviewed: number // open + not reviewed
  false_positives: number // accurate=false
  reviewed: number // any feedback submitted
}

export type AlertBreakdownOptions = {
  // Exclude alerts managers already reviewed as inaccurate/false positive from
  // aggregate pressure counts. This is useful for management trend reports,
  // where overturned alerts should not keep driving coaching urgency.
  excludeInaccurate?: boolean
}

export async function fetchAlertBreakdown(
  scope: UserScope,
  startDate: Date,
  endDate: Date,
  options: AlertBreakdownOptions = {},
): Promise<AlertBreakdownCell[]> {
  if (!scope.isGodMode && scope.managedAgents.length === 0) return []

  // Paginated — Supabase caps each response at 1000 rows, and a multi-day
  // window across many agents readily exceeds that.
  const rows = await fetchAllPaginated<{
    module_name: string | null
    agent_email: string | null
    has_violation: boolean | null
    is_reviewed: boolean | null
    accurate: boolean | null
  }>((from, to) => {
    let q = sb
      .from('eavesly_alerts_with_feedback')
      .select(
        'module_name, agent_email, has_violation, is_reviewed, accurate, alert_created_at',
      )
      .eq('has_violation', true)
      .gte('alert_created_at', startOfBusinessDay(startDate).toISOString())
      .lte('alert_created_at', endOfBusinessDay(endDate).toISOString())
      .order('alert_created_at', { ascending: false })
      .range(from, to)
    for (const moduleName of ALWAYS_SUPPRESSED_ALERT_MODULES) {
      q = q.neq('module_name', moduleName)
    }
    if (!scope.isGodMode) {
      for (const moduleName of SUPER_ADMIN_ONLY_ALERT_MODULES) {
        q = q.neq('module_name', moduleName)
      }
    }
    if (options.excludeInaccurate) q = q.or('accurate.is.null,accurate.eq.true')
    if (!scope.isGodMode) q = q.in('agent_email', scope.managedAgents)
    return q
  })

  const byKey = new Map<string, AlertBreakdownCell>()
  for (const r of rows) {
    if (!r.module_name || !r.agent_email) continue
    const key = `${r.module_name}::${r.agent_email}`
    const existing = byKey.get(key) || {
      module: r.module_name,
      agent_email: r.agent_email,
      agent_full_name: null,
      total: 0,
      unreviewed: 0,
      false_positives: 0,
      reviewed: 0,
    }
    existing.total += 1
    if (!r.is_reviewed) existing.unreviewed += 1
    if (r.is_reviewed) existing.reviewed += 1
    if (r.accurate === false) existing.false_positives += 1
    byKey.set(key, existing)
  }

  return Array.from(byKey.values())
}

// ---- display labels ----

export const VIOLATION_TYPE_LABELS: Record<string, string> = {
  manager_escalation: 'Manager escalation',
  budget_compliance: 'Budget compliance',
  warm_transfer: 'Warm transfer',
  litigation_check: 'Litigation check',
  program_expectations: 'Program expectations',
  achieve_welcome_call: 'Achieve welcome call',
}

export const MODULE_LABELS: Record<string, string> = {
  full_qa: 'Full QA',
  budget_inputs: 'Budget inputs',
  warm_transfer: 'Warm transfer',
  litigation_check: 'Litigation check',
  program_expectations: 'Program expectations',
  achieve_welcome_call_qa: 'Achieve Welcome Call QA',
}

export const ACTION_TAKEN_LABELS: Record<string, string> = {
  coached: 'Coached the agent',
  escalated: 'Escalated',
  follow_up_later: 'Will follow up later',
  no_action_needed: 'No action needed',
}

export const INACCURACY_REASON_LABELS: Record<string, string> = {
  soft_inquiry_misclassified: 'Soft inquiry misclassified',
  wrong_context: 'Wrong context',
  evidence_misquoted: 'Evidence misquoted',
  policy_does_not_apply: "Policy doesn't apply",
  addressed_off_call: 'Covered on a prior call',
  covered_not_verbatim: 'Covered, not read verbatim',
  call_dropped_incomplete: 'Call dropped / enrollment incomplete',
  other: 'Other',
}

// ---- result_json helpers ----

export function extractEvidence(violationType: string, result: any): string {
  if (!result) return ''
  switch (violationType) {
    case 'manager_escalation': {
      const areas = result?.call_overview?.manager_focus_areas
      return Array.isArray(areas)
        ? areas.map((a: any) => a?.quote).filter(Boolean).join('; ')
        : ''
    }
    case 'budget_compliance':
      return result?.key_evidence_quote || ''
    case 'warm_transfer':
      return result?.warm_transfer_compliance?.violation_reason || ''
    case 'litigation_check':
      return result?.key_evidence_quote || ''
    case 'program_expectations':
      return result?.key_evidence_quote || ''
    default:
      return ''
  }
}

export function extractReason(violationType: string, result: any): string {
  if (!result) return ''
  switch (violationType) {
    case 'manager_escalation':
      return result?.call_overview?.manager_review_reason || ''
    case 'budget_compliance':
      return result?.violation_reason || ''
    case 'warm_transfer':
      return result?.warm_transfer_compliance?.violation_reason || ''
    case 'litigation_check':
      return result?.violation_reason || ''
    case 'program_expectations':
      return result?.violation_reason || ''
    default:
      return ''
  }
}
