import { supabase } from '@/integrations/supabase/client'
import type {
  AlertWithFeedback,
  AlertFeedbackInput,
} from '@/types/database'

// The Database<> type is autogenerated and may not yet include the new view +
// table created in 20260427120000_eavesly_alert_feedback.sql. Until types are
// regenerated, we cast at call sites — same pragmatic approach the rest of
// this codebase uses.
const sb = supabase as any

export type UserScope = {
  email: string
  isGodMode: boolean
  managedAgents: string[]
}

export async function fetchUserScope(email: string): Promise<UserScope> {
  const [agentsRes, promptRes] = await Promise.all([
    sb
      .from('agent_manager_mapping')
      .select('agent_email')
      .eq('manager_email', email),
    sb
      .from('manager_coaching_prompts')
      .select('is_god_mode')
      .eq('manager_email', email)
      .maybeSingle(),
  ])

  return {
    email,
    isGodMode: !!promptRes?.data?.is_god_mode,
    managedAgents: (agentsRes?.data ?? []).map((a: any) => a.agent_email),
  }
}

export type AlertFilters = {
  startDate: Date
  endDate: Date
  modules?: string[]
  status?: 'all' | 'new' | 'reviewed'
  accuracy?: 'all' | 'accurate' | 'inaccurate'
  search?: string
}

export async function fetchAlerts(
  filters: AlertFilters,
  scope: UserScope,
): Promise<AlertWithFeedback[]> {
  // Manager with no mapped agents (and not god-mode) sees nothing.
  if (!scope.isGodMode && scope.managedAgents.length === 0) return []

  let q = sb
    .from('eavesly_alerts_with_feedback')
    .select('*')
    .gte('alert_created_at', filters.startDate.toISOString())
    .lte('alert_created_at', filters.endDate.toISOString())
    .order('alert_created_at', { ascending: false })
    .limit(500)

  if (!scope.isGodMode) {
    q = q.in('agent_email', scope.managedAgents)
  }

  if (filters.modules?.length) q = q.in('module_name', filters.modules)
  if (filters.status === 'new') q = q.eq('is_reviewed', false)
  if (filters.status === 'reviewed') q = q.eq('is_reviewed', true)
  if (filters.accuracy === 'accurate') q = q.eq('accurate', true)
  if (filters.accuracy === 'inaccurate') q = q.eq('accurate', false)

  if (filters.search?.trim()) {
    const t = `%${filters.search.trim()}%`
    q = q.or(
      `contact_phone.ilike.${t},sfdc_lead_id.ilike.${t},call_id.ilike.${t},agent_email.ilike.${t}`,
    )
  }

  const { data, error } = await q
  if (error) {
    console.error('Error fetching alerts:', error)
    return []
  }
  return (data || []) as AlertWithFeedback[]
}

export async function fetchAlertOne(
  callId: string,
  moduleName: string,
): Promise<AlertWithFeedback | null> {
  const { data, error } = await sb
    .from('eavesly_alerts_with_feedback')
    .select('*')
    .eq('call_id', callId)
    .eq('module_name', moduleName)
    .maybeSingle()
  if (error) {
    console.error('Error fetching alert:', error)
    return null
  }
  return (data as AlertWithFeedback) ?? null
}

export async function submitAlertFeedback(
  input: AlertFeedbackInput,
): Promise<{ ok: boolean; error?: string }> {
  const payload = {
    call_id: input.call_id,
    module_name: input.module_name,
    manager_email: input.manager_email,
    accurate: input.accurate,
    action_taken: input.accurate ? input.action_taken ?? null : null,
    inaccuracy_reason: !input.accurate ? input.inaccuracy_reason ?? null : null,
    comment: input.comment?.trim() || null,
    reviewed_at: new Date().toISOString(),
  }
  const { error } = await sb
    .from('eavesly_alert_feedback')
    .upsert(payload, { onConflict: 'call_id,module_name' })
  if (error) {
    console.error('Error submitting feedback:', error)
    return { ok: false, error: error.message }
  }
  return { ok: true }
}

// ---- display labels ----

export const VIOLATION_TYPE_LABELS: Record<string, string> = {
  manager_escalation: 'Manager escalation',
  budget_compliance: 'Budget compliance',
  warm_transfer: 'Warm transfer',
  litigation_check: 'Litigation check',
  program_expectations: 'Program expectations',
}

export const MODULE_LABELS: Record<string, string> = {
  full_qa: 'Full QA',
  budget_inputs: 'Budget inputs',
  warm_transfer: 'Warm transfer',
  litigation_check: 'Litigation check',
  program_expectations: 'Program expectations',
}

export const ACTION_TAKEN_LABELS: Record<string, string> = {
  coached: 'Coached the agent',
  escalated: 'Escalated',
  follow_up_later: 'Will follow up later',
  no_action_needed: 'No action needed',
}

export const INACCURACY_REASON_LABELS: Record<string, string> = {
  soft_inquiry_misclassified: 'Soft inquiry misclassified',
  wrong_context: 'Wrong context',
  evidence_misquoted: 'Evidence misquoted',
  policy_does_not_apply: "Policy doesn't apply",
  addressed_off_call: 'Already addressed off-call',
  other: 'Other',
}

// ---- result_json helpers ----

export function extractEvidence(violationType: string, result: any): string {
  if (!result) return ''
  switch (violationType) {
    case 'manager_escalation': {
      const areas = result?.call_overview?.manager_focus_areas
      return Array.isArray(areas)
        ? areas.map((a: any) => a?.quote).filter(Boolean).join('; ')
        : ''
    }
    case 'budget_compliance':
      return result?.key_evidence_quote || ''
    case 'warm_transfer':
      return result?.warm_transfer_compliance?.violation_reason || ''
    case 'litigation_check':
      return result?.key_evidence_quote || ''
    case 'program_expectations':
      return result?.key_evidence_quote || ''
    default:
      return ''
  }
}

export function extractReason(violationType: string, result: any): string {
  if (!result) return ''
  switch (violationType) {
    case 'manager_escalation':
      return result?.call_overview?.manager_review_reason || ''
    case 'budget_compliance':
      return result?.violation_reason || ''
    case 'warm_transfer':
      return result?.warm_transfer_compliance?.violation_reason || ''
    case 'litigation_check':
      return result?.violation_reason || ''
    case 'program_expectations':
      return result?.violation_reason || ''
    default:
      return ''
  }
}
