import { test, expect } from '@playwright/test'
import { alertRow, genericAlertRow, reviewFixture } from './review-fixture'

test('dropdown typing never navigates and Full QA ignores generic verdict shortcuts', async ({ page }) => {
  const state = await reviewFixture(page, [alertRow('polish-first'), alertRow('polish-next')])
  await page.goto('/dashboard/alerts/polish-first/full_qa?status=awaiting_manager')
  await expect(page.getByRole('group', { name: 'Was this alert warranted?', exact: true })).toBeVisible()
  await page.keyboard.press('y')
  await page.keyboard.press('1')
  await expect(page.getByRole('group', { name: 'Was this alert warranted?', exact: true }).getByRole('radio', { checked: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Close (Esc)', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goto('/dashboard/alerts/polish-first/full_qa?status=awaiting_manager')
  await page.getByRole('radio', { name: 'Yes, the alert was warranted', exact: true }).check()
  const add = page.getByRole('article', { name: 'Credit pull consent', exact: true }).getByRole('button', { name: 'Add as coaching issue' })
  await add.click()
  const category = page.getByRole('combobox', { name: 'Finding 1 category' })
  await category.focus()
  let confirmations = 0
  page.on('dialog', async dialog => { confirmations++; await dialog.dismiss() })
  await page.keyboard.press('j')
  await page.keyboard.press('k')
  await expect(page).toHaveURL(/polish-first\/full_qa/)
  await expect(category).toBeFocused()
  expect(confirmations).toBe(0)
  expect(state.writes).toEqual([])
})

test('adding an issue keeps evidence in view and verdict fields reveal without losing drafts', async ({ page }, testInfo) => {
  const state = await reviewFixture(page, [alertRow('polish-form')])
  await page.setViewportSize({ width: 1366, height: 768 })
  await page.goto('/dashboard/alerts/polish-form/full_qa')
  await expect(page.getByRole('article', { name: 'Credit pull consent', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('polished-review-entry.png') })
  await expect(page.getByRole('textbox', { name: 'Explain your decision', exact: true })).toHaveCount(0)
  await page.getByRole('radio', { name: 'Yes, the alert was warranted', exact: true }).check()
  const criterion = page.getByRole('article', { name: 'Credit pull consent', exact: true })
  await criterion.getByRole('button', { name: 'Add as coaching issue' }).click()
  const edit = criterion.getByRole('button', { name: 'Edit coaching issue 1' })
  await expect(edit).toBeFocused()
  await expect(edit).toBeInViewport()
  await edit.click()
  await expect(page.getByRole('textbox', { name: 'Finding 1 summary' })).toBeFocused()
  await page.getByRole('radio', { name: 'No, the alert was unnecessary', exact: true }).check()
  const reason = page.getByRole('textbox', { name: 'Explain your decision', exact: true })
  await reason.fill('The original evidence does not support this escalation.')
  await expect(reason).toHaveAccessibleDescription(/12.*4,000/)
  const description = page.locator(`[id="${await reason.getAttribute('aria-describedby')}"]`)
  expect(await description.evaluate(el => getComputedStyle(el).position)).toBe('absolute')
  await page.getByRole('radio', { name: 'Yes, the alert was warranted', exact: true }).check()
  await expect(page.getByRole('textbox', { name: 'What happened?', exact: true })).toHaveCount(0)
  await page.getByRole('radiogroup', { name: 'Action taken', exact: true }).getByRole('radio', { name: 'Coached the agent', exact: true }).check()
  await page.getByRole('textbox', { name: 'What action did you take?', exact: true }).fill('Discussed the specific issue with the representative.')
  for (const width of [320, 375, 414, 768, 1440]) {
    await page.setViewportSize({ width, height: width < 768 ? 812 : 900 })
    if (width === 320) await page.getByRole('button', { name: 'Review', exact: true }).click()
    await page.getByRole('textbox', { name: 'What action did you take?', exact: true }).scrollIntoViewIfNeeded()
    expect(await page.getByRole('dialog').evaluate(element => getComputedStyle(element).overflow)).toBe('hidden')
    await expect(page.getByRole('button', { name: width < 640 ? 'Back to alerts' : 'Close (Esc)', exact: true })).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`polished-form-${width}.png`) })
  }
  await page.getByText('Discussion', { exact: true }).click()
  await page.getByRole('textbox', { name: 'Add a message', exact: true }).fill('An unsent discussion draft must not move the fixed header.')
  expect(await page.getByRole('dialog').evaluate(element => getComputedStyle(element).overflow)).toBe('hidden')
  await expect(page.getByRole('button', { name: 'Close (Esc)', exact: true })).toBeInViewport()
  await page.getByRole('radio', { name: 'No, the alert was unnecessary', exact: true }).check()
  await expect(reason).toHaveValue('The original evidence does not support this escalation.')
  expect(state.writes).toEqual([])
})

test('all review types use instant keyboard/deep-link motion and the same scrim', async ({ page }) => {
  const state = await reviewFixture(page, [alertRow('full-motion'), genericAlertRow('side-motion', { violation_type: 'budget_compliance' })])
  await page.goto('/dashboard/alerts/full-motion/full_qa?status=awaiting_manager')
  const scrim = () => page.locator('[data-state="open"].fixed.inset-0').filter({ hasNot: page.getByRole('heading') }).first()
  const fullColor = await scrim().evaluate(el => getComputedStyle(el).backgroundColor)
  await page.goto('/dashboard/alerts/side-motion/budget_inputs?status=awaiting_manager')
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.getByRole('dialog').evaluate(el => getComputedStyle(el).animationName)).toBe('none')
  expect(await scrim().evaluate(el => getComputedStyle(el).backgroundColor)).toBe(fullColor)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Review Budget compliance alert for Example side-motion/ }).click()
  expect(await page.getByRole('dialog').evaluate(el => getComputedStyle(el).animationDuration)).toBe('0.22s')
  await page.keyboard.press('Escape')
  expect(state.writes).toEqual([])
})

test('mobile queue shows a useful first row without a screen of scope controls', async ({ page }, testInfo) => {
  const state = await reviewFixture(page, [alertRow('mobile-work')])
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/dashboard/alerts?range=outstanding&status=awaiting_manager')
  await expect(page.getByRole('button', { name: 'Outstanding', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Date range', exact: true })).toBeVisible()
  const first = page.getByRole('button', { name: /Review .* Example mobile-work/ })
  await expect(first).toBeVisible()
  expect((await first.boundingBox())?.y).toBeLessThan(550)
  await page.getByText('Outstanding by next action', { exact: true }).click()
  await expect(page.getByRole('button', { name: 'Filter all-time First reviews 1' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Filter all-time .* 0$/ })).toHaveCount(0)
  await page.getByText('Outstanding by next action', { exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('polished-mobile-queue.png') })
  expect(state.writes).toEqual([])
})

test('queue projects compact reasons and never presents a newer Full QA reason as the reviewed source', async ({ page }) => {
  const state = await reviewFixture(page, [
    alertRow('unreviewed'),
    genericAlertRow('budget', { violation_type: 'budget_compliance', result_json: { violation_reason: 'Budget fields conflict with the customer statement.' } }),
    genericAlertRow('transfer', { module_name: 'warm_transfer', violation_type: 'warm_transfer', result_json: { warm_transfer_compliance: { violation_reason: 'The transfer introduction was missing.' } } }),
    alertRow('reviewed', { is_reviewed: true, accurate: false, feedback_by: 'manager@example.test', violation_details: 'Reviewed the original source and documented the context.', result_json: { call_overview: { manager_review_reason: 'NEWER EVALUATION MUST NOT LEAK' } } }),
    alertRow('system', { is_reviewed: true, accurate: true, feedback_by: 'system@pennie', feedback_comment: 'System-closed without manager review.' }),
    alertRow('legacy', { is_reviewed: true, accurate: null, feedback_by: 'manager@example.test', result_json: { call_overview: { manager_review_reason: 'NEWER EVALUATION MUST NOT LEAK' } } }),
    genericAlertRow('missing', { result_json: null }),
    genericAlertRow('malformed', { violation_type: 'budget_compliance', result_json: { violation_reason: { unexpected: true } } }),
  ])
  await page.goto('/dashboard/alerts?status=all')
  const row = (id: string) => page.getByRole('button', { name: new RegExp(`Review .* alert for Example ${id}$`) })
  await expect(row('unreviewed')).toContainText('Why flagged: Review both quoted passages in context.')
  await expect(row('budget')).toContainText('Why flagged: Budget fields conflict with the customer statement.')
  await expect(row('transfer')).toContainText('Why flagged: The transfer introduction was missing.')
  await expect(row('reviewed')).toContainText('Manager review: Reviewed the original source')
  for (const id of ['legacy', 'missing', 'malformed', 'system']) await expect(row(id)).toContainText('Call summary: Synthetic call')
  await expect(page.getByText('NEWER EVALUATION MUST NOT LEAK')).toHaveCount(0)
  const projection = state.requests.find(url => url.searchParams.get('select')?.includes('feedback_comment'))?.searchParams.get('select')?.split(',') ?? []
  expect(projection).toContain('reason_escalation:result_json->call_overview->>manager_review_reason')
  expect(projection).toContain('reason_direct:result_json->>violation_reason')
  expect(projection).toContain('reason_warm_transfer:result_json->warm_transfer_compliance->>violation_reason')
  for (const heavy of ['*', 'result_json', 'recording_link', 'transcript_url']) expect(projection).not.toContain(heavy)
  expect(state.requests.filter(url => url.pathname.endsWith('/eavesly_alerts_with_feedback') && url.searchParams.get('select') === '*')).toHaveLength(0)
  // A successful save refreshes the list cache from select(*), without projection aliases.
  await row('budget').click()
  await page.getByRole('radio', { name: 'Unnecessary (N)', exact: true }).click()
  await page.getByRole('radio', { name: /Wrong context/ }).click()
  await page.getByRole('textbox', { name: /Why was the alert unnecessary/ }).fill('The fields were clarified later in the same call.')
  await page.getByRole('button', { name: 'Save review', exact: true }).click()
  await expect.poll(() => state.writes.length).toBe(1)
  await expect(page.getByText('Review saved')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(row('budget')).toContainText('Why flagged: Budget fields conflict with the customer statement.')
})

test('a blank coaching issue exposes its required criterion picker', async ({ page }) => {
  const state = await reviewFixture(page, [alertRow('blank-finding')])
  await page.goto('/dashboard/alerts/blank-finding/full_qa')
  await page.getByRole('radio', { name: 'Yes, the alert was warranted', exact: true }).check()
  await page.getByRole('button', { name: 'Add an issue', exact: true }).click()
  const consent = page.getByRole('checkbox', { name: 'Credit pull consent', exact: true })
  await expect(consent).toBeVisible()
  await consent.check()
  await expect(consent).toBeVisible()
  await expect(consent).toBeFocused()
  await page.getByRole('checkbox', { name: 'Call recording disclosure', exact: true }).check()
  await expect(consent).toBeVisible()
  await expect(consent).toBeChecked()
  await expect(page.getByRole('button', { name: 'Add another issue', exact: true })).toBeVisible()
  expect(state.writes).toEqual([])
})

test('Team prioritizes representative outcomes, keeps mobile filters reachable, and makes zero counts static', async ({ page }, testInfo) => {
  const state = await reviewFixture(page, [alertRow('team-pending')], { dailyMetrics: [{ agent_email: 'agent@example.test', agent_full_name: 'Agent Alpha', bucket_day: '2026-09-04', call_count: 10, reviewable_call_count: 9, qa_count: 8 }] })
  await page.goto('/dashboard/team?start=2026-08-09&end=2026-09-07')
  const outcomes = page.getByRole('region', { name: 'Alerts by representative', exact: true })
  await expect(outcomes.getByRole('button', { name: 'Filter Agent Alpha Awaiting manager 1', exact: true })).toBeVisible()
  await expect(outcomes.getByRole('button', { name: /Filter Agent Alpha .* 0$/ })).toHaveCount(0)
  const trends = page.getByText('AI trends and call metrics', { exact: true })
  expect((await trends.boundingBox())!.y).toBeGreaterThan((await outcomes.boundingBox())!.y)
  for (const width of [320, 375, 414, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    const filters = page.getByRole('group', { name: 'Quick filters' })
    await filters.getByRole('button', { name: 'All agents', exact: true }).focus()
    await page.keyboard.press('Tab')
    await page.keyboard.press('Tab')
    await page.keyboard.press('Tab')
    await expect(filters.getByRole('button', { name: 'Has open alerts', exact: true })).toBeFocused()
    await expect(filters.getByRole('button', { name: 'Has open alerts', exact: true })).toBeInViewport({ ratio: 1 })
    await page.keyboard.press('Enter')
    await expect(outcomes.getByRole('button', { name: 'Filter Agent Alpha Awaiting manager 1', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`polished-team-${width}.png`) })
  }
  expect(state.writes).toEqual([])
})
