// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miikotqnovnixpeqtqnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1paWtvdHFub3ZuaXhwZXF0cW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzIxMjksImV4cCI6MjA2ODk0ODEyOX0.gW1KrtqW2HkpcWik088eI-aFQnmsggBujrDY4wLeZIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});